import { Router } from 'express';
import authRoutes from './auth.routes.js';
import userRoutes from './user.routes.js';
import contentRoutes from './content.routes.js';
import campaignRoutes from './campaign.routes.js';
import agentRoutes from './agent.routes.js';
import matchingRoutes from './matching.routes.js';
import communityRoutes from './community.routes.js';
import dashboardRoutes from './dashboard.routes.js';
import accountRoutes from './account.routes.js';
import ideaRoutes from './idea.routes.js';
import listeningRoutes from './listening.routes.js';
import competitiveRoutes from './competitive.routes.js';
import teamRoutes from './team.routes.js';
import startpageRoutes from './startpage.routes.js';
import notificationRoutes from './notification.routes.js';
import usageRoutes from './usage.routes.js';
import settingsRoutes from './settings.routes.js';
import mediaRoutes from './media.routes.js';
import revenueRoutes from './revenue.routes.js';
import webhookRoutes from './webhook.routes.js';
import rssRoutes from './rss.routes.js';
import publicApiRoutes from './public-api.routes.js';
import studioRoutes from './studio.routes.js';
const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/content', contentRoutes);
router.use('/campaigns', campaignRoutes);
router.use('/agents', agentRoutes);
router.use('/matching', matchingRoutes);
router.use('/community', communityRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/accounts', accountRoutes);
router.use('/ideas', ideaRoutes);
router.use('/listening', listeningRoutes);
router.use('/competitive', competitiveRoutes);
router.use('/teams', teamRoutes);
router.use('/startpages', startpageRoutes);
router.use('/notifications', notificationRoutes);
router.use('/usage', usageRoutes);
router.use('/settings', settingsRoutes);
router.use('/media', mediaRoutes);
router.use('/revenue', revenueRoutes);
router.use('/webhooks', webhookRoutes);
router.use('/rss', rssRoutes);
router.use('/public', publicApiRoutes);
router.use('/studio', studioRoutes);

export default router;
