import PDFDocument from 'pdfkit';
import { prisma } from '../config/index.js';

export async function generateInvoicePdf(invoiceId: string): Promise<Buffer> {
  const invoice = await prisma.invoice.findUnique({
    where: { id: invoiceId },
    include: {
      brandDeal: true,
      creatorProfile: { include: { user: { select: { name: true, email: true } } } },
    },
  });

  if (!invoice) throw new Error('Invoice not found');

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const creatorName = invoice.creatorProfile?.user?.name ?? 'Creator';
    const creatorEmail = invoice.creatorProfile?.user?.email ?? '';

    // ─── Header ─────────────────────────────────────────────
    doc.fontSize(24).fillColor('#6366f1').text('INVOICE', 50, 50);
    doc.fontSize(10).fillColor('#64748b')
      .text(`Invoice #: ${invoice.invoiceNumber}`, 50, 85)
      .text(`Date: ${invoice.issuedAt ? new Date(invoice.issuedAt).toLocaleDateString() : new Date(invoice.createdAt).toLocaleDateString()}`, 50, 100)
      .text(`Status: ${invoice.status}`, 50, 115);

    if (invoice.dueDate) {
      doc.text(`Due Date: ${new Date(invoice.dueDate).toLocaleDateString()}`, 50, 130);
    }

    // ─── From (Creator) ─────────────────────────────────────
    doc.fontSize(11).fillColor('#334155').text('From:', 50, 165);
    doc.fontSize(10).fillColor('#475569')
      .text(creatorName, 50, 182)
      .text(creatorEmail, 50, 197);

    // ─── To (Brand) ─────────────────────────────────────────
    doc.fontSize(11).fillColor('#334155').text('To:', 300, 165);
    doc.fontSize(10).fillColor('#475569');
    if (invoice.brandDeal) {
      doc.text(invoice.brandDeal.brandName, 300, 182);
      if (invoice.brandDeal.contactEmail) {
        doc.text(invoice.brandDeal.contactEmail, 300, 197);
      }
    }

    // ─── Line ───────────────────────────────────────────────
    doc.moveTo(50, 225).lineTo(545, 225).strokeColor('#e2e8f0').stroke();

    // ─── Table Header ───────────────────────────────────────
    const tableTop = 245;
    doc.fontSize(10).fillColor('#334155');
    doc.text('Description', 50, tableTop);
    doc.text('Amount', 430, tableTop, { width: 115, align: 'right' });

    doc.moveTo(50, tableTop + 18).lineTo(545, tableTop + 18).strokeColor('#e2e8f0').stroke();

    // ─── Line Items ─────────────────────────────────────────
    let y = tableTop + 30;

    if (invoice.brandDeal) {
      const deliverables = invoice.brandDeal.deliverables ?? [];
      if (deliverables.length > 0) {
        for (const item of deliverables) {
          doc.fontSize(10).fillColor('#475569').text(item, 50, y);
          y += 18;
        }
      } else {
        doc.fontSize(10).fillColor('#475569').text(`Services for ${invoice.brandDeal.brandName}`, 50, y);
        y += 18;
      }
    } else {
      doc.fontSize(10).fillColor('#475569').text('Professional Services', 50, y);
      y += 18;
    }

    if (invoice.notes) {
      doc.fontSize(9).fillColor('#94a3b8').text(`Note: ${invoice.notes}`, 50, y);
      y += 18;
    }

    // ─── Total ──────────────────────────────────────────────
    doc.moveTo(50, y + 10).lineTo(545, y + 10).strokeColor('#e2e8f0').stroke();

    y += 25;
    doc.fontSize(14).fillColor('#334155').text('Total:', 350, y);
    doc.fontSize(14).fillColor('#6366f1').text(
      `${invoice.currency} ${invoice.amount.toLocaleString()}`,
      430, y, { width: 115, align: 'right' },
    );

    if (invoice.paidAt) {
      y += 30;
      doc.fontSize(12).fillColor('#22c55e').text('PAID', 430, y, { width: 115, align: 'right' });
      doc.fontSize(9).fillColor('#94a3b8').text(
        `Paid on ${new Date(invoice.paidAt).toLocaleDateString()}`,
        350, y + 18, { width: 195, align: 'right' },
      );
    }

    // ─── Footer ─────────────────────────────────────────────
    doc.fontSize(8).fillColor('#94a3b8')
      .text('Generated by CrMS · Creator Management System', 50, 750, { align: 'center' });

    doc.end();
  });
}
