export enum Role {
  CREATOR = 'CREATOR',
  BRAND = 'BRAND',
  AGENCY = 'AGENCY',
  ADMIN = 'ADMIN',
}

export enum Platform {
  INSTAGRAM = 'INSTAGRAM',
  YOUTUBE = 'YOUTUBE',
  TIKTOK = 'TIKTOK',
  TWITTER = 'TWITTER',
  LINKEDIN = 'LINKEDIN',
  THREADS = 'THREADS',
  BLUESKY = 'BLUESKY',
  FACEBOOK = 'FACEBOOK',
  PINTEREST = 'PINTEREST',
  REDDIT = 'REDDIT',
}

export enum PostStatus {
  IDEA = 'IDEA',
  DRAFT = 'DRAFT',
  REVIEW = 'REVIEW',
  APPROVED = 'APPROVED',
  SCHEDULED = 'SCHEDULED',
  PUBLISHED = 'PUBLISHED',
  FAILED = 'FAILED',
}

export enum PostType {
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  REEL = 'REEL',
  STORY = 'STORY',
  CAROUSEL = 'CAROUSEL',
  SHORT = 'SHORT',
  THREAD = 'THREAD',
}

export enum IdeaStatus {
  SPARK = 'SPARK',
  DEVELOPING = 'DEVELOPING',
  READY = 'READY',
  ARCHIVED = 'ARCHIVED',
}

export enum CampaignStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum CampaignStage {
  BRIEF = 'BRIEF',
  RECRUITING = 'RECRUITING',
  IN_PROGRESS = 'IN_PROGRESS',
  REVIEW = 'REVIEW',
  COMPLETED = 'COMPLETED',
}

export enum DeliverableStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  REVISION_REQUESTED = 'REVISION_REQUESTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum DeliverableType {
  POST = 'POST',
  STORY = 'STORY',
  REEL = 'REEL',
  VIDEO = 'VIDEO',
  REVIEW = 'REVIEW',
  UNBOXING = 'UNBOXING',
  TUTORIAL = 'TUTORIAL',
  OTHER = 'OTHER',
}

export enum MatchStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  COMPLETED = 'COMPLETED',
}

export enum AgentType {
  CONTENT_GENERATION = 'CONTENT_GENERATION',
  PUBLISHING = 'PUBLISHING',
  SCHEDULING = 'SCHEDULING',
  MATCHING = 'MATCHING',
  ANALYTICS = 'ANALYTICS',
  ENGAGEMENT = 'ENGAGEMENT',
  TREND_DETECTION = 'TREND_DETECTION',
  LISTENING = 'LISTENING',
  COMPETITIVE = 'COMPETITIVE',
  CAMPAIGN = 'CAMPAIGN',
  COLLABORATION = 'COLLABORATION',
  LINK_IN_BIO = 'LINK_IN_BIO',
  GROWTH = 'GROWTH',
  STUDIO = 'STUDIO',
}

export enum InteractionType {
  COMMENT = 'COMMENT',
  DM = 'DM',
  MENTION = 'MENTION',
  EMAIL = 'EMAIL',
  WHATSAPP = 'WHATSAPP',
  BRAND_INQUIRY = 'BRAND_INQUIRY',
}

export enum Sentiment {
  POSITIVE = 'POSITIVE',
  NEGATIVE = 'NEGATIVE',
  NEUTRAL = 'NEUTRAL',
  QUESTION = 'QUESTION',
}

export enum MentionIntent {
  BUYING = 'BUYING',
  QUESTION = 'QUESTION',
  COMPLAINT = 'COMPLAINT',
  PRAISE = 'PRAISE',
  COLLAB = 'COLLAB',
  OTHER = 'OTHER',
}

export enum SignalType {
  TREND = 'TREND',
  LEAD = 'LEAD',
  RISK = 'RISK',
  VIRAL_POST = 'VIRAL_POST',
}

export enum SignalStatus {
  NEW = 'NEW',
  ACTIONED = 'ACTIONED',
  IGNORED = 'IGNORED',
}

export enum ContactType {
  BRAND = 'BRAND',
  FAN = 'FAN',
  CREATOR = 'CREATOR',
  AGENCY = 'AGENCY',
  OTHER = 'OTHER',
}

export enum ContactSource {
  DM = 'DM',
  COMMENT = 'COMMENT',
  MENTION = 'MENTION',
  EMAIL = 'EMAIL',
  IMPORT = 'IMPORT',
  MANUAL = 'MANUAL',
}

export enum DealStatus {
  PROSPECT = 'PROSPECT',
  CONTACTED = 'CONTACTED',
  LEAD = 'LEAD',
  NEGOTIATING = 'NEGOTIATING',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  DELIVERED = 'DELIVERED',
  PAID = 'PAID',
  CANCELLED = 'CANCELLED',
  LOST = 'LOST',
}

export enum OAuthProvider {
  GOOGLE = 'GOOGLE',
  INSTAGRAM = 'INSTAGRAM',
  YOUTUBE = 'YOUTUBE',
  TIKTOK = 'TIKTOK',
  TWITTER = 'TWITTER',
  LINKEDIN = 'LINKEDIN',
  THREADS = 'THREADS',
  BLUESKY = 'BLUESKY',
  FACEBOOK = 'FACEBOOK',
  PINTEREST = 'PINTEREST',
  MASTODON = 'MASTODON',
  MICROSOFT = 'MICROSOFT',
  OKTA = 'OKTA',
}

export enum TeamRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  EDITOR = 'EDITOR',
  CONTRIBUTOR = 'CONTRIBUTOR',
  VIEWER = 'VIEWER',
}

export enum ApprovalStatus {
  NONE = 'NONE',
  PENDING_REVIEW = 'PENDING_REVIEW',
  CHANGES_REQUESTED = 'CHANGES_REQUESTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
